version: '3.8'
services:
  database:
    image: mysql:latest
    volumes:
      - database-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=my_secret_pw
      - MYSQL_DATABASE=h2o
    networks:
      - h2o_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8040:8040"
    depends_on:
      - database
    networks:
      - h2o_network

volumes:
  database-data:

networks:
  h2o_network:
