version: '3.8'
services:
  database:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - database-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=my_secret_pw
      - MYSQL_DATABASE=h2o
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8040:8080"
volumes:
  database-data: